# Generated by Django 5.1.2 on 2024-10-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thegame',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thegame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thegame',
            name='outcome',
            field=models.CharField(blank=True, choices=[('white_win', 'White Wins'), ('black_win', 'Black Wins'), ('tie', 'Tie'), ('ongoing', 'Ongoing')], max_length=10, null=True),
        ),
    ]
