# Generated by Django 5.1.2 on 2024-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_application', '0002_thegame_loser_thegame_winner_alter_thegame_outcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thegame',
            old_name='journal',
            new_name='black_journal',
        ),
        migrations.AddField(
            model_name='thegame',
            name='white_journal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
